basic/models/Pattern.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pattern".
 *
 * @property string $name
 * @property integer $id
 *
 * @property PatternColumn[] $patternColumns
 * @property Row[] $rows
 */
class Pattern extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pattern';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string'],
            [['start_with'], 'integer'],
            [['extension'], 'string', 'max' => 5],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => 'Имя шаблона',
            'id' => 'ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPatternColumns()
    {
        return $this->hasMany(PatternColumn::className(), ['pattern_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRows()
    {
        return $this->hasMany(Row::className(), ['pattern_id' => 'id']);
    }
}

basic/controllers/PatternController.php
<?php

namespace app\controllers;

use app\models\PatternColumn;
use Yii;
use app\models\Pattern;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PatternController implements the CRUD actions for Pattern model.
 */
class PatternController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pattern models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Pattern::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pattern model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pattern model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pattern();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    public function actionCreateColumn($pattern_id)
    {
        $model = new PatternColumn(['pattern_id'=>$pattern_id]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->pattern_id]);
        } else {
            return $this->render('create_column', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pattern model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pattern model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    public function actionDeleteColumn($column_id)
    {
        $model = PatternColumn::findOne(['id'=>$column_id]);
        $pat_id = $model->pattern_id;
        $model->delete();

        return $this->redirect(['view','id'=>$pat_id]);
    }

    /**
     * Finds the Pattern model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pattern the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pattern::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/controllers/RowController.php
<?php

namespace app\controllers;

use app\models\Files;
use app\models\Pattern;
use Yii;
use app\models\Row;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RowController implements the CRUD actions for Row model.
 */
class RowController extends Controller
{
    public function actionIndex($pattern_id)
    {
        $columns = [];
        $pattern = Pattern::findOne($pattern_id);
        $query = Row::find()
            //->orderBy(['row.datetime'=>SORT_DESC])
            ->asArray();
        $query->andWhere(['pattern_id'=>$pattern_id]);
        $query->leftJoin('files','files.id = row.file_id');
        foreach ($pattern->patternColumns as $column){
            $query->addSelect([
                $column->name=>new Expression("( SELECT VALUE from row_data where row_data.pattern_column_id = $column->id and row_id = row.id)")
            ]);
            $columns[]=$column->name;
        }
        $query->addSelect(['row.datetime']);
        $query->addSelect(['file_id'=>'files.id']);
        $query->addSelect(['id'=>'row.id']);

        $query->addSelect(['file_name'=>'files.name']);
        $columns[] = 'datetime';
        $columns[] = [
            'attribute'=>'file_name',
            'format'=>'raw',
            'value'=>function($data){
                return Html::a($data['file_name'],['file/view','id'=>$data['file_id']]);
            }
        ];


        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'pattern'=>$pattern,
            'columns'=>$columns
        ]);
    }
}

basic/views/pattern/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Pattern */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pattern-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput() ?>

    <?= $form->field($model, 'extension')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'start_with')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton( 'Сохранить', ['class' =>'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/pattern/_list.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;


?>
<button  class="list-group-item">
    <?= Html::encode($model->name) ?>
    <a  href="<?= \yii\helpers\Url::to(['delete-column','column_id'=>$model->id]) ?>" class="pull-right">x</a>
</button>

basic/views/pattern/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Pattern */

$this->title = 'Создать шаблон';
$this->params['breadcrumbs'][] = ['label' => 'Шаблоны', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pattern-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/pattern/create_column.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\PatternColumn */

$this->title = 'Редактирование колонки ('.$model->pattern->name.')';
$this->params['breadcrumbs'][] = ['label' => 'Шаблоны', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pattern-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = \yii\widgets\ActiveForm::begin(); ?>
    <?= $form->field($model, 'name')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php \yii\widgets\ActiveForm::end(); ?>
</div>

basic/views/pattern/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Шаблоны';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pattern-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать шаблон', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name:ntext',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

basic/views/pattern/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pattern */

$this->title = 'Update Pattern: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Patterns', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pattern-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/pattern/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pattern */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Шаблоны', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pattern-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить колонку', ['create-column','pattern_id'=>$model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Просмотр данных', ['row/index','pattern_id'=>$model->id], ['class' => 'btn btn-primary']) ?>

    </p>
    <?php
    $dataProvider = new \yii\data\ActiveDataProvider([
        'query' => \app\models\PatternColumn::find()->where(['pattern_id'=>$model->id])->orderBy('id DESC'),
        'pagination' => false,
    ]);
?>
    <div class="list-group">
    <?php
        echo \yii\widgets\ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_list',
        ]);
    ?>
    </div>



</div>